# Generated by Django 3.2.4 on 2022-12-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInternetIession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('MAC', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('usage_time', models.TimeField()),
                ('download', models.DecimalField(decimal_places=2, max_digits=12)),
                ('upload', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
